name: Desplegar en GitHub Pages

on:
  push:
    branches:
      - main # O la rama principal que utilices

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Hacer checkout del código
      - name: Checkout del código
        uses: actions/checkout@v2

      # 2. Actualizar la versión del Service Worker
      - name: Actualizar versión del Service Worker
        run: |

          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "Nueva versión: $VERSION"
          # Suponemos que el Service Worker se encuentra en la raíz del proyecto con el nombre "service-worker.js".
          # Si la ruta es distinta, modifícala en la siguiente línea.
          sed -i "s/const CACHE_NAME = \"dieta-cache-v[^\"]*\"/const CACHE_NAME = \"dieta-cache-v$VERSION\"/g" service-worker.js
          echo "Service Worker actualizado con CACHE_NAME = dieta-cache-v${VERSION}"

      # 3. Mostrar los primeros 5 renglones del Service Worker (opcional, para depuración)
      - name: Mostrar contenido del Service Worker actualizado
        run: |
          head -n 5 service-worker.js

      # 4. Desplegar a GitHub Pages
      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Ajusta este directorio según la ubicación de tus archivos estáticos
