name: Test Simple Trigger

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo ">>> TEST WORKFLOW TRIGGERED SUCCESSFULLY on branch ${GITHUB_REF##*/}"
