name: Desplegar en GitHub Pages (DEV)

on:
  # Disparador manual per poder provar-ho
  workflow_dispatch:

  # Disparador automàtic quan fas push a la branca main
  push:
    branches:
      - main

# Permisos necessaris perquè el workflow pugui escriure a la branca gh-pages
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    name: Build and Deploy (DEV)
    runs-on: ubuntu-latest
    steps:
      # 1. Descarrega el codi de la teva branca 'main'
      - name: Checkout del codi
        uses: actions/checkout@v4

      # 2. Actualitza la versió del Service Worker (el teu pas personalitzat)
      - name: Actualizar versió del Service Worker
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "Nova versió del Service Worker: $VERSION"
          sed -i "s/const CACHE_NAME = \"dieta-cache-v[^\"]*\"/const CACHE_NAME = \"dieta-cache-v$VERSION\"/g" service-worker.js
          echo "Service Worker actualitzat."

      # 3. Desplega el contingut a la branca 'gh-pages'
      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          # Aquesta línia és clau: assegura que el domini correcte està configurat
          cname: dev.misdietas.com
