# .github/workflows/deploy.yml

name: Test Workflow Trigger
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Workflow triggered!"
